//
//  main.c
//  Euler Project Question 2
//
//  Created by Richer  on 2013-06-06.
//  Copyright (c) 2013 Richer Larivère. All rights reserved.
//

#include <stdio.h>

int main(int argc, const char * argv[])
{
    /*
     Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
     
     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
     
     By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
     */
    const long int VALEUR_LIMITE = 4000000;
    int x = 0;
    int y = 1;
    int z;
    int Somme = 0;
    
    do
    {
        z = x + y;
        x = y;
        y = z;
        if (y % 2 == 0) Somme += y;
    } while (y <= VALEUR_LIMITE);
    
    printf("La réponse de la somme des nombres pairs n'excédant pas 4000000 de la suite de fibonacci est %d",Somme);
    
    return 0;
}